package dev.cominotti.java.evo;

import dev.cominotti.java.evo.validation.CnpjRules;
import dev.cominotti.java.evo.validation.CpfRules;
import dev.cominotti.java.evo.validation.EmailRules;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that Hibernate {@code @AttributeBinderType} column binders set correct
 * column metadata (name, length, nullable) in the generated DDL.
 *
 * <p>This test queries H2's {@code INFORMATION_SCHEMA.COLUMNS} to inspect the actual
 * column definitions generated by Hibernate. Each EVO field on the {@code Greeting}
 * entity uses a custom {@code @*Column} annotation (e.g., {@code @EmailColumn},
 * {@code @CpfColumn}) whose binder hardcodes the column length from the corresponding
 * {@code *Rules} constant.</p>
 *
 * <p>This replaces the previous {@code AttributeOverrideColumnInheritanceTest} that
 * documented the JPA {@code @AttributeOverride} length-reset bug. With the new
 * {@code @AttributeBinderType} approach, column lengths are always correct.</p>
 */
@DataJpaTest
class AttributeOverrideColumnInheritanceTest {

    @Autowired
    private JdbcTemplate jdbc;

    @Test
    void emailColumnHasCorrectLength() {
        assertColumnLength("EMAIL", EmailRules.MAX_LENGTH);
    }

    @Test
    void cpfColumnHasCorrectLength() {
        assertColumnLength("AUTHOR_CPF", CpfRules.DIGIT_COUNT);
    }

    @Test
    void cnpjColumnHasCorrectLength() {
        assertColumnLength("COMPANY_CNPJ", CnpjRules.DIGIT_COUNT);
    }

    @Test
    void taxIdColumnHasCorrectLength() {
        assertColumnLength("TAX_ID", CnpjRules.DIGIT_COUNT);
    }

    @Test
    void explicitlyNullableColumnsAllowNull() {
        // Greeting marks all EVO fields as nullable = true (they are optional in this example).
        // @EvoColumn defaults to NOT NULL, so nullable = true must be explicit.
        for (var col : new String[]{"EMAIL", "AUTHOR_CPF", "COMPANY_CNPJ", "TAX_ID"}) {
            var nullable = jdbc.queryForObject(
                    "SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS "
                            + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                    String.class, col);
            assertThat(nullable)
                    .as("Column %s should be nullable (explicit nullable = true)", col)
                    .isEqualTo("YES");
        }
    }

    @Test
    void binderSetColumnNamesCorrectly() {
        for (var expectedColumn : new String[]{"EMAIL", "AUTHOR_CPF", "COMPANY_CNPJ", "TAX_ID"}) {
            var count = jdbc.queryForObject(
                    "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
                            + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                    Integer.class, expectedColumn);
            assertThat(count)
                    .as("Column %s should exist", expectedColumn)
                    .isEqualTo(1);
        }
    }

    private void assertColumnLength(String columnName, int expectedLength) {
        var length = jdbc.queryForObject(
                "SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS "
                        + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                Integer.class, columnName);
        assertThat(length)
                .as("Column %s should have length %d", columnName, expectedLength)
                .isEqualTo(expectedLength);
    }
}
