package dev.cominotti.java.evo;

import dev.cominotti.java.evo.email.EmailRules;
import dev.cominotti.java.evo.taxid.CnpjRules;
import dev.cominotti.java.evo.taxid.CpfRules;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies that the {@code EvoColumnMetadataIntegrator} auto-derives correct column
 * lengths for EVO fields, and that standard {@code @Column} attributes (name, nullable,
 * explicit length) are respected.
 *
 * <p>Queries H2's {@code INFORMATION_SCHEMA.COLUMNS} to inspect the actual column
 * definitions generated by Hibernate. For EVO types with {@code @Size(max = ...)},
 * the integrator overrides the JPA default length (255) with the derived value.
 * For types without {@code @Size} (e.g., {@code Cpf}, {@code Cnpj}), the entity
 * must set {@code @Column(length = ...)} explicitly.</p>
 */
@DataJpaTest
class AttributeOverrideColumnInheritanceTest {

    @Autowired
    private JdbcTemplate jdbc;

    @Test
    void emailColumnLengthDerivedFromSizeAnnotation() {
        assertColumnLength("EMAIL", EmailRules.MAX_LENGTH);
    }

    @Test
    void cpfColumnHasExplicitLength() {
        assertColumnLength("AUTHOR_CPF", CpfRules.DIGIT_COUNT);
    }

    @Test
    void cnpjColumnHasExplicitLength() {
        assertColumnLength("COMPANY_CNPJ", CnpjRules.DIGIT_COUNT);
    }

    @Test
    void taxIdColumnHasExplicitLength() {
        assertColumnLength("TAX_ID", CnpjRules.DIGIT_COUNT);
    }

    @Test
    void columnsAreNullableByDefault() {
        // @Column defaults to nullable = true (standard JPA behavior).
        // The Greeting entity doesn't set nullable = false on any EVO field.
        for (var col : new String[]{"EMAIL", "AUTHOR_CPF", "COMPANY_CNPJ", "TAX_ID"}) {
            var nullable = jdbc.queryForObject(
                    "SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS "
                            + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                    String.class, col);
            assertThat(nullable)
                    .as("Column %s should be nullable (JPA default)", col)
                    .isEqualTo("YES");
        }
    }

    @Test
    void columnNamesSetCorrectly() {
        for (var expectedColumn : new String[]{"EMAIL", "AUTHOR_CPF", "COMPANY_CNPJ", "TAX_ID"}) {
            var count = jdbc.queryForObject(
                    "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
                            + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                    Integer.class, expectedColumn);
            assertThat(count)
                    .as("Column %s should exist", expectedColumn)
                    .isEqualTo(1);
        }
    }

    private void assertColumnLength(String columnName, int expectedLength) {
        var length = jdbc.queryForObject(
                "SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS "
                        + "WHERE TABLE_NAME = 'GREETING' AND COLUMN_NAME = ?",
                Integer.class, columnName);
        assertThat(length)
                .as("Column %s should have length %d", columnName, expectedLength)
                .isEqualTo(expectedLength);
    }
}
